### ISSUE TITLE
RD configurator

### ISSUE THREAD

**Issue by AngelaAprea** [rickdkk/folder-configurator#1]
Bij de laatste release blijft de 'do it'- button uitgegrijsd

**Comment by sophiedkk** [comment]
Dag Angela,

Werkt de 'Load' button wel? Ik heb net snel even gekeken en bij mij werkt de applicatie wel. Het is echter wel belangrijk dat je nu ook de URL van Fontys (https://fontys.data.surfsara.nl/) invoerd in het bovenste vakje. Als dit niet gebeurd dan kan de applicatie geen verbinding maken. Hiervoor geeft die nu geen goede error.

Kan je kijken of het dan wel werkt?

**Comment by AngelaAprea** [comment]
Ja, de loadbutton werkt wel. Bedacht me later...misschien zijn de accounts bij SURF nog niet aangemeld. Dat is gisteren wel doorgegeven, maar mogelijk zijn ze daar wat vertraagd. Ik probeer het morgen nog wel eens.

**Comment by sophiedkk** [comment]
De applicatie kan niet checken of de accounts bestaan (daar zijn geen rechten voor), dus dit zou geen beperkende factor moeten zijn.

De URL is nu instelbaar zodat andere instellingen hun eigen domein in kunnen vullen. Het enige dat ik wel ben tegengekomen is dat als de URL niet klopt hij vastloopt omdat hier geen check op zat, dan werkt de 'do it' button ook niet meer.

**Comment by AngelaAprea** [comment]
![image](https://user-images.githubusercontent.com/125444133/218986512-ee756791-b011-455e-bdbf-6307219e607e.png)

**Comment by sophiedkk** [comment]
OK ik moest even Windows installeren op een pc om de .exe te kunnen testen. Het voorbeeld wat ik had gebruikt om te testen lijkt nog steeds te werken. De lege regel met "/" in je screenshot doet me wel vermoeden dat er een fout in de input file zit. Zou je die nog een keer goed willen checken?

Anders moet ik nog wat aggresiever aan loggen om erachter te komen wat het probleem is. Vooral aangezien ik niet meer bij jullie systemen kan :upside_down_face:

**Comment by AngelaAprea** [comment]
Ik krijg het niet voor elkaar. Blijf dezelfde uitgegrijsde 'do it' button zien. Kunnen we ook team-en of zal ik de dienst vragen het over te nemen?
